grouptest/Controllers/CastController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grouptest.Data;
using grouptest.Models;

namespace grouptest.Controllers
{
    public class CastController : Controller
    {
        ApplicationDbContext _context;

        public CastController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var cast = from a in _context.CastMembers
                       join b in _context.Actors
                       on a.ActorNumber equals b.ActorNumber
                       join c in _context.DvdTitles
                       on a.DvdNumber equals c.DvdNumber

                       select new CastMember
                       {
                           Id = a.Id,
                           ActorNumber = b.ActorNumber,
                           ActorSurname = b.ActorSurname,
                           DvdNumber = c.DvdNumber,
                           DvdTitleName = c.DvdTitleName
                       };
            return View(cast);
        }

        public IActionResult Create()
        {
            ViewData["DvdTitleName"] = new SelectList(_context.DvdTitles, "DvdNumber", "DvdTitleName");
            ViewData["ActorSurname"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CastMember castMember)
        {
            castMember.ActorNumber = int.Parse(castMember.ActorSurname);
            castMember.DvdNumber = int.Parse(castMember.DvdTitleName);
            if (ModelState.IsValid)
            {
                _context.Add(castMember);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(castMember);
        }

        public IActionResult Delete(int id)
        {
            CastMember? castMember = _context.CastMembers.FirstOrDefault(m => m.Id == id);
            if (castMember != null)
            {
                _context.Remove(castMember);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var castMember = await _context.CastMembers.FindAsync(id);
            if (castMember == null)
            {
                return NotFound();
            }
            var cast = from a in _context.CastMembers
                       join b in _context.Actors
                       on a.ActorNumber equals b.ActorNumber
                       join c in _context.DvdTitles
                       on a.DvdNumber equals c.DvdNumber
                       where a.Id == castMember.Id
                       select new CastMember
                       {
                           Id = a.Id,
                           ActorNumber = b.ActorNumber,
                           ActorSurname = b.ActorSurname,
                           DvdNumber = c.DvdNumber,
                           DvdTitleName = c.DvdTitleName
                       };

            castMember = cast.FirstOrDefault(); 
            ViewData["DvdTitleName"] = new SelectList(_context.DvdTitles, "DvdNumber", "DvdTitleName");
            ViewData["ActorSurname"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname");

            return View(castMember);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CastMember castMember)
        {
            if (id != castMember.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    castMember.ActorNumber = int.Parse(castMember.ActorSurname);
                    castMember.DvdNumber = int.Parse(castMember.DvdTitleName);
                    _context.Update(castMember);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CastMemberExists(castMember.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DvdTitleName"] = new SelectList(_context.DvdTitles, "DvdNumber", "DvdTitleName");
            ViewData["ActorSurname"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname");
            return View(castMember);
        }

        private bool CastMemberExists(int id)
        {
            return _context.CastMembers.Any(e => e.Id == id);
        }
    }
}

grouptest/Controllers/LoanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grouptest.Data;
using grouptest.Models;
using grouptest.Models.ViewModels;

namespace grouptest.Controllers
{
    public class LoanController : Controller
    {

        ApplicationDbContext _context;

        public LoanController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var loan = from a in _context.Loans
                       join b in _context.LoanTypes
                       on a.LoanTypeNumber equals b.LoanTypeNumber
                       join c in _context.DvdCopies
                       on a.CopyNumber equals c.CopyNumber
                       join d in _context.Members
                       on a.MemberNumber equals d.MemberNumber

                       select new Loan
                       {
                           LoanNumber = a.LoanNumber,
                           LoanTypeNumber = b.LoanTypeNumber,
                           LoanTypee = b.LoanTypee,
                           CopyNumber = c.CopyNumber,
                           MemberNumber = d.MemberNumber,
                           MemberLastname  = d.MemberLastname,
                           DateOut = a.DateOut,
                           DateDue = a.DateDue,
                           DateReturn = a.DateReturn
                       };
            return View(loan);
        }

        public IActionResult DisplayCharge(ChargeViewModel chargeViewModel)
        {
            return View(chargeViewModel);
        }

        public IActionResult Create()
        {
            ViewData["LoanTypee"] = new SelectList(_context.LoanTypes, "LoanTypeNumber", "LoanTypee");
            ViewData["CopyNumber"] = new SelectList(_context.DvdCopies, "CopyNumber", "CopyNumber");
            ViewData["MemberLastname"] = new SelectList(_context.Members, "MemberNumber", "MemberLastname");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Loan loan)
        {
            loan.LoanTypeNumber = int.Parse(loan.LoanTypee);
            loan.MemberNumber = int.Parse(loan.MemberLastname);


            //Query 6 for showing the charges

            //finding the loantype
            var loanType = _context.LoanTypes.Where(x => x.LoanTypeNumber == loan.LoanTypeNumber).FirstOrDefault();

            //Adding the duration from loan type

            loan.DateDue = loan.DateOut.AddDays(loanType.LoanDuration);

           
            if (ModelState.IsValid)
            {
                _context.Add(loan);
                await _context.SaveChangesAsync();

            }

            //calculating the charge
            var forCharge = from a in _context.Loans
                            join b in _context.DvdCopies
                            on a.CopyNumber equals b.CopyNumber
                            join c in _context.DvdTitles
                            on b.DvdNumber equals c.DvdNumber

                            //descending order for getting the last row at the first
                            orderby a.DateOut descending

                            select new ChargeViewModel
                            {
                                StandardCharge = c.StandardCharge,
                                PenaltyCharge = c.PenaltyCharge,
                                DvdTitleName = c.DvdTitleName,
                                DateDue = a.DateDue,
                                Message = "Please return the DVD on given due date to avoid the penalty charges",
                                TotalCharge = c.StandardCharge * loanType.LoanDuration
                            };
            var oneCharge = forCharge.First();//getting only first data
            return RedirectToAction("DisplayCharge", oneCharge);
        }

        public IActionResult Delete(int id)
        {
            Loan? loan = _context.Loans.FirstOrDefault(m => m.LoanNumber == id);
            if (loan != null)
            {
                _context.Remove(loan);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tloan = await _context.Loans.FindAsync(id);
            if (tloan == null)
            {
                return NotFound();
            }

            var loan = from a in _context.Loans
                       join b in _context.LoanTypes
                       on a.LoanTypeNumber equals b.LoanTypeNumber
                       join c in _context.DvdCopies
                       on a.CopyNumber equals c.CopyNumber
                       join d in _context.Members
                       on a.MemberNumber equals d.MemberNumber

                       where a.LoanNumber == tloan.LoanNumber
                       select new Loan
                       {
                           LoanNumber = a.LoanNumber,
                           LoanTypeNumber = b.LoanTypeNumber,
                           LoanTypee = b.LoanTypee,
                           CopyNumber = c.CopyNumber,
                           MemberNumber = d.MemberNumber,
                           MemberLastname = d.MemberLastname,
                           DateOut = a.DateOut,
                           DateDue = a.DateDue,
                           DateReturn = a.DateReturn
                       };


            tloan = loan.FirstOrDefault();

            ViewData["LoanTypee"] = new SelectList(_context.LoanTypes, "LoanTypeNumber", "LoanTypee");
            ViewData["CopyNumber"] = new SelectList(_context.DvdCopies, "CopyNumber", "CopyNumber");
            ViewData["MemberLastname"] = new SelectList(_context.Members, "MemberNumber", "MemberLastname");
            return View(tloan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Loan loan)
        {
            if (id != loan.LoanNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    loan.LoanTypeNumber = int.Parse(loan.LoanTypee);
                    loan.MemberNumber = int.Parse(loan.MemberLastname);
                    _context.Update(loan);
                    await _context.SaveChangesAsync();

                    //calculating the extra price to pay
                    if (loan.DateReturn > loan.DateDue)
                    {
                       
                        int diff = (int) ((loan.DateReturn?? DateTime.Now) - (loan.DateDue ?? DateTime.Now)).TotalDays;

                        var forCharge = from a in _context.Loans.Where(l => l.LoanNumber == id)
                                        join b in _context.DvdCopies
                                        on a.CopyNumber equals b.CopyNumber
                                        join c in _context.DvdTitles
                                        on b.DvdNumber equals c.DvdNumber

                                        select new ChargeViewModel
                                        {
                                            StandardCharge = c.StandardCharge,
                                            PenaltyCharge = c.PenaltyCharge,
                                            DvdTitleName = c.DvdTitleName,
                                            DateDue = a.DateDue,
                                            DateReturn = a.DateReturn,
                                            Message = "You have been penalty charged",
                                            TotalCharge = c.PenaltyCharge * diff
                                        };
                        var toSendCharge = forCharge.First();
                        return RedirectToAction("DisplayCharge", toSendCharge);

                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoanExists(loan.LoanNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoanTypee"] = new SelectList(_context.LoanTypes, "LoanTypeNumber", "LoanTypee");
            ViewData["CopyNumber"] = new SelectList(_context.DvdCopies, "CopyNumber", "CopyNumber");
            ViewData["MemberLastname"] = new SelectList(_context.Members, "MemberNumber", "MemberLastname");
            return View(loan);
        }

        private bool LoanExists(int id)
        {
            return _context.Loans.Any(e => e.LoanNumber == id);
        }


    }
}

grouptest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/grouptest.styles.css" asp-append-version="true" />
    @RenderSection("Stylesheets", required: false)
    <style>
        .navbar{
            padding: 20px
        }
        .logo{
            width:50px;
            height:50px;
            border-radius:50%;
        }
        .navbar-brand{
            font-size:35px;
            font-weight:bolder;
            font-style:italic;
            font-family: poppin;
            margin: 0px 20px;
        }
        .nav-link{
            font-family:poppin;
            font-weight: bolder;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <li class="container-fluid">
                <div>
                    <img class="logo" src="images/logoo.jpg">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ropey DVDs</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>


                <li class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-light  p-4" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Team
                              </a>
                              <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Actor" asp-action="Index">Actors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Studio" asp-action="Index">Studio</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Producer" asp-action="Index">Producer</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Cast" asp-action="Index">Cast Member</a>
                                </li>
                              </ul>
                         </li>
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-light p-4 " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Members
                              </a>
                              <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Membership" asp-action="Index">Membership Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                                </li>
                              </ul>
                         </li>
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-light p-4" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                DVD
                              </a>
                              <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="DvdCategory" asp-action="Index">DvdCategory</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="DvdTitle" asp-action="Index">DvdTitles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="DvdCopy" asp-action="Index"> DvdCopy</a>
                                </li>

                              </ul>
                         </li>
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-light p-4 " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Loan
                              </a>
                              <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="LoanType" asp-action="Index">LoanTypes</a>
                                </li>
                        
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Loan" asp-action="Index"> Loan</a>
                                </li>

                              </ul>
                         </li>
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-light p-4 " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Functionalities
                              </a>
                              <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionOne"> Function One</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionTwo"> Function Two</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionThree"> Function Three</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionFourView"> Function Four</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionFive"> Function Five</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionEight"> Function Eight</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionTen"> Function Ten</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionEleven"> Function Eleven</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionTwelve"> Function Twelve</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Main" asp-action="FunctionThirteen"> Function Thirteen</a>
                                </li>

                              </ul>
                         </li>
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-light p-4  " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Register
                              </a>
                              <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Authentication" asp-action="RegisterAdmin">Register Admin</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Authentication" asp-action="Register">Register User</a>
                                </li>
                              </ul>
                         </li>
                        <li class="nav-item">
                                <a class="nav-link text-light p-4" asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
                        </li>
                
                    </ul>
                </li>
             </li>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseWorkSampleAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>